services:
  front:
    container_name: medlab-front
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./portfolio-frontend:/app
      - /app/node_modules
    restart: on-failure
